name: cqf-algo-trading
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - python-dotenv
  - matplotlib
  - pyarrow
  - pykalman
  - pip
  - pip:
    - alpaca-trade-api
    - backtrader
