name: cqf-algo-trading
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - python-dotenv
  - matplotlib
  - pyarrow
  - pykalman
  - pyyaml
  - requests
  - urllib3
  - pip
  - pip:
    - alpaca-trade-api
    - backtrader
    - pandas-ta
