name: cqf-algo-trading
channels:
  - conda-forge    # keep conda-forge first so its recipes win
  - defaults       # fall back to the Anaconda defaults channel

dependencies:
  # ===== core scientific stack (all available on conda‑forge) =====
  - python=3.10
  - pandas>=1.5
  - numpy>=1.23
  - pyyaml
  - matplotlib>=3.5
  - seaborn>=0.12
  - requests>=2.28
  - python-dotenv>=0.21
  - yfinance>=0.2
  - pyarrow>=11.0
  - websockets>=10.0
  - aiohttp>=3.8
  - scikit-learn>=1.0
  - scipy>=1.8
  - plotly>=5.0
  - dash>=2.0
  - psutil>=5.8

  # ===== quant / trading libs already packaged for conda =====
  - pandas-ta                     # technical‑analysis helpers
  - redis-py>=4.0                 # conda-forge name for the python redis client
  - pykalman

  # pip fallback – packages that are PyPI‑only (for now) =====
  - pip                           # ensure pip is in the env so the next section works
  - pip:
      - alpaca-trade-api          # Alpaca SDK is only on PyPI
      - backtrader                # backtrader is PyPI‑only
      - asyncio-mqtt>=0.11.0      # not yet on conda‑forge
